---
_ocp4_workload_osac_admin_password: ""
_ocp4_workload_osac_user_password: ""

_ocp4_workload_osac_ui_url: ""
_ocp4_workload_osac_fullfillment_api_url: ""
_ocp4_workload_osac_aap_url: ""
_ocp4_workload_osac_keycloak_url: ""

_bastion_host: ""