---
# ------------------------------------------------
# Register SNO on RHACM
# ------------------------------------------------
ocp4_workload_prepare_hcp_secret_name: hcp
ocp4_workload_prepare_hcp_secret_namespace: hcp

# Pull secret needs to come from variables
ocp4_workload_prepare_hcp_pull_secret: ""
# Public key can be empty
ocp4_workload_prepare_hcp_ssh_public_key: ""

# ------------------------------------------------
# RHACM Policy Configuration for GitOps Operator
# ------------------------------------------------
ocp4_workload_prepare_hcp_policy_namespace: policies
ocp4_workload_prepare_hcp_clusterset_name: managed
ocp4_workload_prepare_hcp_clusterset_binding_namespace: policies

# GitOps Operator Configuration
ocp4_workload_prepare_hcp_gitops_operator_policy_namespace: policies
ocp4_workload_prepare_hcp_gitops_operator_channel: gitops-1.19
ocp4_workload_prepare_hcp_gitops_operator_source: redhat-operators
ocp4_workload_prepare_hcp_gitops_operator_source_namespace: openshift-marketplace
# Clustersets to target with Placement
ocp4_workload_prepare_hcp_gitops_operator_clustersets:
- "{{ ocp4_workload_prepare_hcp_clusterset_name }}"
# Labels to target with Placement
ocp4_workload_prepare_hcp_gitops_operator_placement_labels:
- cloud: Amazon
- cloud: BareMetal

# ------------------------------------------------
# RHACM Policy Configuration for Compliance Operator
# ------------------------------------------------
ocp4_workload_prepare_hcp_compliance_operator_policy_namespace: open-cluster-management-global-set
ocp4_workload_prepare_hcp_compliance_operator_channel: stable
ocp4_workload_prepare_hcp_compliance_operator_source: redhat-operators
ocp4_workload_prepare_hcp_compliance_operator_source_namespace: openshift-marketplace

# Clustersets to target with Placement
ocp4_workload_prepare_hcp_compliance_operator_clustersets:
- global

# Labels to target with Placement
ocp4_workload_prepare_hcp_compliance_operator_placement_labels: []

# ------------------------------------------------
# ApplicationSet for Autoshift
# ------------------------------------------------
ocp4_workload_prepare_hcp_autoshift_version: "0.0.4"
