---
- name: Get virtctl-clidownloads-kubevirt-hyperconverged ConsoleCLIDownload
  kubernetes.core.k8s_info:
    api_version: console.openshift.io/v1
    kind: ConsoleCLIDownload
    name: virtctl-clidownloads-kubevirt-hyperconverged
  register: r_virtctl_cli_download
  retries: 20
  delay: 10
  ignore_errors: true
  until:
  - r_virtctl_cli_download.resources is defined
  - r_virtctl_cli_download.resources | length > 0

- name: Get virtctl download URL from ConsoleCLIDownload
  when: r_virtctl_cli_download.resources | length > 0
  ansible.builtin.set_fact:
    _ocp4_workload_openshift_virtualization_virtctl_url: >-
      {{ r_virtctl_cli_download.resources[0] | to_json | from_json
      | json_query("spec.links[?contains(href,'linux')].href") | first }}

- name: Install virtctl
  become: true
  block:
  - name: Download virtctl cli tool
    ansible.builtin.get_url:
      url: "{{ _ocp4_workload_openshift_virtualization_virtctl_url }}"
      validate_certs: false
      dest: /tmp/virtctl.tar.gz
      mode: ug=rw
    register: r_virtctl
    until: r_virtctl is success
    retries: 20
    delay: 10

  - name: Install virtctl CLI on bastion
    ansible.builtin.unarchive:
      src: /tmp/virtctl.tar.gz
      remote_src: true
      dest: /usr/bin
      mode: ug=rwx,o=rx
      owner: root
      group: root
    args:
      creates: /usr/bin/virtctl

  - name: Remove downloaded file
    ansible.builtin.file:
      state: absent
      path: /tmp/virtctl.tar.gz
