---
- name: Set admin password
  ansible.builtin.set_fact:
    _ocp4_workload_osac_admin_password: >-
      {{ ocp4_workload_osac_admin_password
         | default(
           lookup('password', '/dev/null',
             chars=['ascii_letters', 'digits'],
             length=16
           )
         , true) }}

- name: Set user password
  ansible.builtin.set_fact:
    _ocp4_workload_osac_user_password: >-
      {{ ocp4_workload_osac_user_password
         | default(
           lookup('password', '/dev/null',
             chars=['ascii_letters', 'digits'],
             length=16
           )
         , true) }}
